exclude: null
grid-search:

  "--config":
    - "coma_qmix"

  lr:
    - 0.0001
    - 0.00003
    - 0.00005

  critic_lr:
    - 0.0001
    - 0.00003
    - 0.00005

  td_lambda:
    - 0.6
    - 0.7
    - 0.8 

  buffer_size:
    - 2000
    - 3000
    - 4000

  batch_size_run:
    - 8
    - 16
  
  batch_size:
    - 64
    - 128
    
grid-search-groups:
  env0:
    - "--env-config": "pred_prey_punish"